<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-10 08:40

=======
# Generated by Django 5.2.4 on 2025-07-09 13:27

import django.db.models.deletion
>>>>>>> 52dd3ed4 (first commit)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('teachers', '0001_initial'),
>>>>>>> 52dd3ed4 (first commit)
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
<<<<<<< HEAD
                ('phone_number', models.CharField(max_length=15)),
=======
                ('phone_number', models.CharField(max_length=15, unique=True)),
>>>>>>> 52dd3ed4 (first commit)
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
<<<<<<< HEAD
=======
                ('assigned_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
>>>>>>> 52dd3ed4 (first commit)
            ],
        ),
    ]
