<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-10 08:40

import django.db.models.deletion
=======
# Generated by Django 5.2.4 on 2025-07-09 13:27

import django.db.models.deletion
from django.conf import settings
>>>>>>> 52dd3ed4 (first commit)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
<<<<<<< HEAD
        ('teachers', '0001_initial'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 52dd3ed4 (first commit)
    ]

    operations = [
        migrations.AddField(
            model_name='student',
<<<<<<< HEAD
            name='assigned_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
=======
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
>>>>>>> 52dd3ed4 (first commit)
        ),
    ]
